apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reearth-serve
  namespace: eukarya-inc
  annotations:
    github.com/project-slug: eukarya-inc/reearth-serve
  links:
  - url: https://github.com/eukarya-inc/reearth-serve
    title: GitHub
    icon: github
  - url: https://reearth-serve.reearth.workers.dev
    title: Website
    icon: web
  tags:
  - typescript
spec:
  type: service
  lifecycle: production
  owner: eukarya-inc/cto
