import decodeJpeg, { init as initDecodeJpeg } from "@jsquash/jpeg/decode.js";
import decodePng, { init as initDecodePng } from "@jsquash/png/decode.js";
import decodeWebp, { init as initDecodeWebp } from "@jsquash/webp/decode.js";
import resize, { initResize } from "@jsquash/resize";
import encodeWebp, { init as initEncodeWebp } from "@jsquash/webp/encode.js";

// Cloudflare Workers (and wrangler dev) cannot fetch WASM via file:// URLs;
// jSquash's default `init()` does exactly that. Importing the .wasm modules
// directly gives us a WebAssembly.Module that wrangler bundles into the
// Worker binary, and each codec's init() accepts that module.
// Vite/wrangler can't resolve nested .wasm files via bare-specifier package
// paths (the @jsquash packages don't expose them in `exports`). Reach into
// node_modules via relative path — `.wasm` imports are bundled by wrangler
// into the Worker binary at build time.
import jpegDecWasm from "../../node_modules/@jsquash/jpeg/codec/dec/mozjpeg_dec.wasm";
// The PNG / resize packages ship .wasm.d.ts files that describe the module's
// internal exports (named functions), shadowing the generic `*.wasm`
// declaration in env.d.ts. At bundle time wrangler still provides the
// WebAssembly.Module via default import, so the runtime is fine.
// @ts-expect-error — see comment above
import pngDecWasm from "../../node_modules/@jsquash/png/codec/pkg/squoosh_png_bg.wasm";
import webpDecWasm from "../../node_modules/@jsquash/webp/codec/dec/webp_dec.wasm";
import webpEncWasm from "../../node_modules/@jsquash/webp/codec/enc/webp_enc.wasm";
// @ts-expect-error — same as png above
import resizeWasm from "../../node_modules/@jsquash/resize/lib/resize/pkg/squoosh_resize_bg.wasm";

import { THUMBNAIL_LONG_EDGE, THUMBNAIL_QUALITY, THUMBNAIL_SIZES, type ThumbnailSize } from "./sizes";

let wasmInitialized: Promise<void> | null = null;
function ensureWasm(): Promise<void> {
  if (wasmInitialized) return wasmInitialized;
  // Each init() is idempotent once the module is registered.
  wasmInitialized = Promise.all([
    initDecodeJpeg(jpegDecWasm as unknown as WebAssembly.Module),
    initDecodePng(pngDecWasm as unknown as WebAssembly.Module),
    initDecodeWebp(webpDecWasm as unknown as WebAssembly.Module),
    initEncodeWebp(webpEncWasm as unknown as WebAssembly.Module),
    initResize(resizeWasm as unknown as WebAssembly.Module),
  ]).then(() => undefined);
  return wasmInitialized;
}

export interface GeneratedThumbnail {
  size: ThumbnailSize;
  data: ArrayBuffer;
  width: number;
  height: number;
}

// Decode → resize → encode. Returns thumbnails for sizes whose long edge is
// not larger than the source (we never upscale). Sizes are produced in
// ascending order; the largest one is generated by resizing the original,
// and each smaller size is derived from the previous result for speed and
// quality (one big downscale per pyramid step instead of one per size from
// the original).
export async function generateThumbnails(
  source: ArrayBuffer,
  contentType: string,
): Promise<GeneratedThumbnail[]> {
  await ensureWasm();
  const original = await decode(source, contentType);
  const longEdge = Math.max(original.width, original.height);

  // Build pyramid largest → smallest, skipping sizes that exceed the source.
  const targets = THUMBNAIL_SIZES.filter((s) => THUMBNAIL_LONG_EDGE[s] < longEdge);
  if (targets.length === 0) {
    // Source is smaller than all thumbnail sizes — emit a single xs at the
    // source's own dimensions so consumers still get a usable thumb.
    const encoded = await encodeWebp(original, { quality: THUMBNAIL_QUALITY.xs });
    return [{ size: "xs", data: encoded, width: original.width, height: original.height }];
  }

  const results: GeneratedThumbnail[] = [];
  // Iterate largest first so each step downsamples from the previous result.
  let current: ImageData = original;
  const orderedLargestFirst = [...targets].reverse();
  for (const size of orderedLargestFirst) {
    const target = computeDims(current.width, current.height, THUMBNAIL_LONG_EDGE[size]);
    current = await resize(current, { width: target.width, height: target.height });
    const encoded = await encodeWebp(current, { quality: THUMBNAIL_QUALITY[size] });
    results.push({ size, data: encoded, width: current.width, height: current.height });
  }
  // Caller-friendly: return ascending order.
  return results.reverse();
}

async function decode(buffer: ArrayBuffer, contentType: string): Promise<ImageData> {
  const base = contentType.split(";")[0].trim().toLowerCase();
  switch (base) {
    case "image/jpeg":
      return decodeJpeg(buffer);
    case "image/png":
      return decodePng(buffer);
    case "image/webp":
      return decodeWebp(buffer);
    case "image/gif":
      // GIF support: jSquash does not ship a GIF decoder, so fall back to the
      // runtime's built-in ImageDecoder. Workers does not expose ImageDecoder
      // (browsers do), so for now GIF is unsupported on the Worker path. The
      // Container path (Phase 4) handles GIF via libvips.
      throw new Error("GIF decoding requires the container path");
    default:
      throw new Error(`Unsupported source content type: ${contentType}`);
  }
}

function computeDims(srcWidth: number, srcHeight: number, longEdge: number): { width: number; height: number } {
  if (srcWidth >= srcHeight) {
    const width = Math.min(srcWidth, longEdge);
    const height = Math.max(1, Math.round((width / srcWidth) * srcHeight));
    return { width, height };
  }
  const height = Math.min(srcHeight, longEdge);
  const width = Math.max(1, Math.round((height / srcHeight) * srcWidth));
  return { width, height };
}
