#!/usr/bin/env tsx
// Generates the gzip-compressible extension list from jshttp/mime-db plus
// domain-specific extras in scripts/compressible-extras.json.
//
// Outputs:
//   shared/compressible-extensions.generated.ts
//   container/archive-extractor/compressible_generated.go
//
// Run: npm run gen:compressible

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import db from "mime-db";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");

// MIME types we explicitly skip even when compressible=true, because their
// `extensions` list pulls in formats we don't want to gzip (executables, etc.).
const SKIP_MIME_TYPES = new Set<string>([
  "application/octet-stream",
]);

function collectFromMimeDb(): Map<string, string> {
  const out = new Map<string, string>();
  for (const [mime, entry] of Object.entries(db)) {
    if (!entry.compressible) continue;
    if (SKIP_MIME_TYPES.has(mime)) continue;
    if (!entry.extensions) continue;
    for (const ext of entry.extensions) {
      const k = ext.toLowerCase();
      if (!out.has(k)) out.set(k, mime);
    }
  }
  return out;
}

interface ExtrasFile {
  [section: string]: { _note?: string; extensions: string[] } | string;
}

function collectFromExtras(): Map<string, string> {
  const out = new Map<string, string>();
  const path = resolve(__dirname, "compressible-extras.json");
  const json: ExtrasFile = JSON.parse(readFileSync(path, "utf8"));
  for (const [section, value] of Object.entries(json)) {
    if (typeof value === "string") continue; // top-level _comment
    if (section === "_exclude") continue; // handled separately
    for (const ext of value.extensions) {
      out.set(ext.toLowerCase(), `extras:${section}`);
    }
  }
  return out;
}

function collectExcludes(): Set<string> {
  const path = resolve(__dirname, "compressible-extras.json");
  const json: ExtrasFile = JSON.parse(readFileSync(path, "utf8"));
  const ex = json._exclude;
  if (!ex || typeof ex === "string") return new Set();
  return new Set(ex.extensions.map((e) => e.toLowerCase()));
}

function merge(): { ext: string; source: string }[] {
  const fromDb = collectFromMimeDb();
  const fromExtras = collectFromExtras();
  const excludes = collectExcludes();
  const all = new Map<string, string>();
  for (const [k, v] of fromDb) {
    if (excludes.has(k)) continue;
    all.set(k, v);
  }
  for (const [k, v] of fromExtras) {
    if (excludes.has(k)) continue;
    if (!all.has(k)) all.set(k, v);
  }
  return [...all.entries()]
    .map(([ext, source]) => ({ ext, source }))
    .sort((a, b) => a.ext.localeCompare(b.ext));
}

function emitTS(entries: { ext: string; source: string }[]): string {
  const lines = entries.map(({ ext }) => `  "${ext}",`).join("\n");
  return `// Code generated by scripts/gen-compressible.ts. DO NOT EDIT.
// Source: jshttp/mime-db + scripts/compressible-extras.json
// Run \`npm run gen:compressible\` to regenerate.

export const COMPRESSIBLE_EXTENSIONS: ReadonlySet<string> = new Set([
${lines}
]);
`;
}

function emitGo(entries: { ext: string; source: string }[]): string {
  const longest = Math.max(...entries.map((e) => e.ext.length + 1));
  const lines = entries
    .map(({ ext }) => {
      const key = `".${ext}":`;
      const pad = " ".repeat(Math.max(1, longest + 3 - key.length));
      return `\t${key}${pad}true,`;
    })
    .join("\n");
  return `// Code generated by scripts/gen-compressible.ts. DO NOT EDIT.
// Source: jshttp/mime-db + scripts/compressible-extras.json
// Run \`npm run gen:compressible\` to regenerate.

package main

var compressibleExtensions = map[string]bool{
${lines}
}
`;
}

function main() {
  const entries = merge();
  const tsPath = resolve(repoRoot, "shared/compressible-extensions.generated.ts");
  const goPath = resolve(repoRoot, "container/archive-extractor/compressible_generated.go");
  writeFileSync(tsPath, emitTS(entries));
  writeFileSync(goPath, emitGo(entries));
  console.log(`Wrote ${entries.length} extensions:`);
  console.log(`  ${tsPath}`);
  console.log(`  ${goPath}`);
}

main();
