import type { FileStorage, MetadataStore, VersionStore, UploadSessionStore, PresignedUrlGenerator } from "./asset/repository";
import type { JobStore } from "./job/repository";
import type { AuthUser } from "./auth/types";
import type { Authorizer } from "./auth/authorizer";
import type { ProjectStore } from "./project/repository";
import type { WorkspaceStore } from "./workspace/repository";
import type { MemberStore } from "./member/repository";
import type { StorageUsageStore } from "./infra/d1";
import type { CleanupPendingStore } from "./cleanup/repository";
export type AppEnv = {
  Variables: {
    metadata: MetadataStore;
    versions: VersionStore;
    storage: FileStorage;
    uploadSessions: UploadSessionStore;
    presignedUrls: PresignedUrlGenerator | null;
    jobs: JobStore;
    ttlSeconds: number;
    baseUrl: string;
    user: AuthUser | null;
    sessionId: string | null;
    authorizer: Authorizer;
    projects: ProjectStore;
    workspaces: WorkspaceStore;
    members: MemberStore;
    extractionQueue: Queue | null;
    storageUsage: StorageUsageStore;
    pendingCleanup: CleanupPendingStore;
    anonymousUploadEnabled: boolean;
  };
};
